/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as V2RouteImport } from './routes/v2'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ResourcesWhitePapersRouteImport } from './routes/resources.white-papers'
import { Route as ResourcesGlossaryRouteImport } from './routes/resources.glossary'
import { Route as ResourcesEventsWebinarsRouteImport } from './routes/resources.events-webinars'
import { Route as ResourcesCaseStudiesRouteImport } from './routes/resources.case-studies'
import { Route as ResourcesBlogsRouteImport } from './routes/resources.blogs'
import { Route as MicrosoftPowerBiRouteImport } from './routes/microsoft.power-bi'
import { Route as MicrosoftPowerAppsRouteImport } from './routes/microsoft.power-apps'
import { Route as MicrosoftD365FoRouteImport } from './routes/microsoft.d365-fo'
import { Route as MicrosoftD365CrmRouteImport } from './routes/microsoft.d365-crm'
import { Route as MicrosoftD365BcRouteImport } from './routes/microsoft.d365-bc'
import { Route as MicrosoftAzureRouteImport } from './routes/microsoft.azure'
import { Route as CybersecurityThreatdownRouteImport } from './routes/cybersecurity.threatdown'
import { Route as CybersecurityMicrosoftSecurityRouteImport } from './routes/cybersecurity.microsoft-security'
import { Route as CybersecurityFirecompassRouteImport } from './routes/cybersecurity.firecompass'
import { Route as CybersecurityBarracudaRouteImport } from './routes/cybersecurity.barracuda'
import { Route as CustomerExperienceXeboRouteImport } from './routes/customer-experience.xebo'
import { Route as CustomerExperienceView360RouteImport } from './routes/customer-experience.view360'
import { Route as AiProvakilRouteImport } from './routes/ai.provakil'
import { Route as AiDuneDynamicsRouteImport } from './routes/ai.dune-dynamics'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin.index'
import { Route as ResourcesWhitePapersSlugRouteImport } from './routes/resources.white-papers.$slug'
import { Route as ResourcesGlossarySlugRouteImport } from './routes/resources.glossary.$slug'
import { Route as ResourcesEventsWebinarsSlugRouteImport } from './routes/resources.events-webinars.$slug'
import { Route as ResourcesCaseStudiesSlugRouteImport } from './routes/resources.case-studies.$slug'
import { Route as ResourcesBlogsSlugRouteImport } from './routes/resources.blogs.$slug'
import { Route as AuthenticatedAdminWhitePapersRouteImport } from './routes/_authenticated/admin.white-papers'
import { Route as AuthenticatedAdminUsersRouteImport } from './routes/_authenticated/admin.users'
import { Route as AuthenticatedAdminGlossaryRouteImport } from './routes/_authenticated/admin.glossary'
import { Route as AuthenticatedAdminEventsRouteImport } from './routes/_authenticated/admin.events'
import { Route as AuthenticatedAdminCaseStudiesRouteImport } from './routes/_authenticated/admin.case-studies'
import { Route as AuthenticatedAdminBlogsRouteImport } from './routes/_authenticated/admin.blogs'
import { Route as AuthenticatedAdminWhitePapersNewRouteImport } from './routes/_authenticated/admin.white-papers.new'
import { Route as AuthenticatedAdminWhitePapersIdRouteImport } from './routes/_authenticated/admin.white-papers.$id'
import { Route as AuthenticatedAdminGlossaryNewRouteImport } from './routes/_authenticated/admin.glossary.new'
import { Route as AuthenticatedAdminGlossaryIdRouteImport } from './routes/_authenticated/admin.glossary.$id'
import { Route as AuthenticatedAdminEventsNewRouteImport } from './routes/_authenticated/admin.events.new'
import { Route as AuthenticatedAdminEventsIdRouteImport } from './routes/_authenticated/admin.events.$id'
import { Route as AuthenticatedAdminCaseStudiesNewRouteImport } from './routes/_authenticated/admin.case-studies.new'
import { Route as AuthenticatedAdminCaseStudiesIdRouteImport } from './routes/_authenticated/admin.case-studies.$id'
import { Route as AuthenticatedAdminBlogsNewRouteImport } from './routes/_authenticated/admin.blogs.new'
import { Route as AuthenticatedAdminBlogsIdRouteImport } from './routes/_authenticated/admin.blogs.$id'

const V2Route = V2RouteImport.update({
  id: '/v2',
  path: '/v2',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ResourcesWhitePapersRoute = ResourcesWhitePapersRouteImport.update({
  id: '/resources/white-papers',
  path: '/resources/white-papers',
  getParentRoute: () => rootRouteImport,
} as any)
const ResourcesGlossaryRoute = ResourcesGlossaryRouteImport.update({
  id: '/resources/glossary',
  path: '/resources/glossary',
  getParentRoute: () => rootRouteImport,
} as any)
const ResourcesEventsWebinarsRoute = ResourcesEventsWebinarsRouteImport.update({
  id: '/resources/events-webinars',
  path: '/resources/events-webinars',
  getParentRoute: () => rootRouteImport,
} as any)
const ResourcesCaseStudiesRoute = ResourcesCaseStudiesRouteImport.update({
  id: '/resources/case-studies',
  path: '/resources/case-studies',
  getParentRoute: () => rootRouteImport,
} as any)
const ResourcesBlogsRoute = ResourcesBlogsRouteImport.update({
  id: '/resources/blogs',
  path: '/resources/blogs',
  getParentRoute: () => rootRouteImport,
} as any)
const MicrosoftPowerBiRoute = MicrosoftPowerBiRouteImport.update({
  id: '/microsoft/power-bi',
  path: '/microsoft/power-bi',
  getParentRoute: () => rootRouteImport,
} as any)
const MicrosoftPowerAppsRoute = MicrosoftPowerAppsRouteImport.update({
  id: '/microsoft/power-apps',
  path: '/microsoft/power-apps',
  getParentRoute: () => rootRouteImport,
} as any)
const MicrosoftD365FoRoute = MicrosoftD365FoRouteImport.update({
  id: '/microsoft/d365-fo',
  path: '/microsoft/d365-fo',
  getParentRoute: () => rootRouteImport,
} as any)
const MicrosoftD365CrmRoute = MicrosoftD365CrmRouteImport.update({
  id: '/microsoft/d365-crm',
  path: '/microsoft/d365-crm',
  getParentRoute: () => rootRouteImport,
} as any)
const MicrosoftD365BcRoute = MicrosoftD365BcRouteImport.update({
  id: '/microsoft/d365-bc',
  path: '/microsoft/d365-bc',
  getParentRoute: () => rootRouteImport,
} as any)
const MicrosoftAzureRoute = MicrosoftAzureRouteImport.update({
  id: '/microsoft/azure',
  path: '/microsoft/azure',
  getParentRoute: () => rootRouteImport,
} as any)
const CybersecurityThreatdownRoute = CybersecurityThreatdownRouteImport.update({
  id: '/cybersecurity/threatdown',
  path: '/cybersecurity/threatdown',
  getParentRoute: () => rootRouteImport,
} as any)
const CybersecurityMicrosoftSecurityRoute =
  CybersecurityMicrosoftSecurityRouteImport.update({
    id: '/cybersecurity/microsoft-security',
    path: '/cybersecurity/microsoft-security',
    getParentRoute: () => rootRouteImport,
  } as any)
const CybersecurityFirecompassRoute =
  CybersecurityFirecompassRouteImport.update({
    id: '/cybersecurity/firecompass',
    path: '/cybersecurity/firecompass',
    getParentRoute: () => rootRouteImport,
  } as any)
const CybersecurityBarracudaRoute = CybersecurityBarracudaRouteImport.update({
  id: '/cybersecurity/barracuda',
  path: '/cybersecurity/barracuda',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomerExperienceXeboRoute = CustomerExperienceXeboRouteImport.update({
  id: '/customer-experience/xebo',
  path: '/customer-experience/xebo',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomerExperienceView360Route =
  CustomerExperienceView360RouteImport.update({
    id: '/customer-experience/view360',
    path: '/customer-experience/view360',
    getParentRoute: () => rootRouteImport,
  } as any)
const AiProvakilRoute = AiProvakilRouteImport.update({
  id: '/ai/provakil',
  path: '/ai/provakil',
  getParentRoute: () => rootRouteImport,
} as any)
const AiDuneDynamicsRoute = AiDuneDynamicsRouteImport.update({
  id: '/ai/dune-dynamics',
  path: '/ai/dune-dynamics',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const ResourcesWhitePapersSlugRoute =
  ResourcesWhitePapersSlugRouteImport.update({
    id: '/$slug',
    path: '/$slug',
    getParentRoute: () => ResourcesWhitePapersRoute,
  } as any)
const ResourcesGlossarySlugRoute = ResourcesGlossarySlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => ResourcesGlossaryRoute,
} as any)
const ResourcesEventsWebinarsSlugRoute =
  ResourcesEventsWebinarsSlugRouteImport.update({
    id: '/$slug',
    path: '/$slug',
    getParentRoute: () => ResourcesEventsWebinarsRoute,
  } as any)
const ResourcesCaseStudiesSlugRoute =
  ResourcesCaseStudiesSlugRouteImport.update({
    id: '/$slug',
    path: '/$slug',
    getParentRoute: () => ResourcesCaseStudiesRoute,
  } as any)
const ResourcesBlogsSlugRoute = ResourcesBlogsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => ResourcesBlogsRoute,
} as any)
const AuthenticatedAdminWhitePapersRoute =
  AuthenticatedAdminWhitePapersRouteImport.update({
    id: '/white-papers',
    path: '/white-papers',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminUsersRoute = AuthenticatedAdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminGlossaryRoute =
  AuthenticatedAdminGlossaryRouteImport.update({
    id: '/glossary',
    path: '/glossary',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminEventsRoute =
  AuthenticatedAdminEventsRouteImport.update({
    id: '/events',
    path: '/events',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminCaseStudiesRoute =
  AuthenticatedAdminCaseStudiesRouteImport.update({
    id: '/case-studies',
    path: '/case-studies',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminBlogsRoute = AuthenticatedAdminBlogsRouteImport.update({
  id: '/blogs',
  path: '/blogs',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminWhitePapersNewRoute =
  AuthenticatedAdminWhitePapersNewRouteImport.update({
    id: '/new',
    path: '/new',
    getParentRoute: () => AuthenticatedAdminWhitePapersRoute,
  } as any)
const AuthenticatedAdminWhitePapersIdRoute =
  AuthenticatedAdminWhitePapersIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => AuthenticatedAdminWhitePapersRoute,
  } as any)
const AuthenticatedAdminGlossaryNewRoute =
  AuthenticatedAdminGlossaryNewRouteImport.update({
    id: '/new',
    path: '/new',
    getParentRoute: () => AuthenticatedAdminGlossaryRoute,
  } as any)
const AuthenticatedAdminGlossaryIdRoute =
  AuthenticatedAdminGlossaryIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => AuthenticatedAdminGlossaryRoute,
  } as any)
const AuthenticatedAdminEventsNewRoute =
  AuthenticatedAdminEventsNewRouteImport.update({
    id: '/new',
    path: '/new',
    getParentRoute: () => AuthenticatedAdminEventsRoute,
  } as any)
const AuthenticatedAdminEventsIdRoute =
  AuthenticatedAdminEventsIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => AuthenticatedAdminEventsRoute,
  } as any)
const AuthenticatedAdminCaseStudiesNewRoute =
  AuthenticatedAdminCaseStudiesNewRouteImport.update({
    id: '/new',
    path: '/new',
    getParentRoute: () => AuthenticatedAdminCaseStudiesRoute,
  } as any)
const AuthenticatedAdminCaseStudiesIdRoute =
  AuthenticatedAdminCaseStudiesIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => AuthenticatedAdminCaseStudiesRoute,
  } as any)
const AuthenticatedAdminBlogsNewRoute =
  AuthenticatedAdminBlogsNewRouteImport.update({
    id: '/new',
    path: '/new',
    getParentRoute: () => AuthenticatedAdminBlogsRoute,
  } as any)
const AuthenticatedAdminBlogsIdRoute =
  AuthenticatedAdminBlogsIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => AuthenticatedAdminBlogsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/v2': typeof V2Route
  '/admin': typeof AuthenticatedAdminRouteWithChildren
  '/ai/dune-dynamics': typeof AiDuneDynamicsRoute
  '/ai/provakil': typeof AiProvakilRoute
  '/customer-experience/view360': typeof CustomerExperienceView360Route
  '/customer-experience/xebo': typeof CustomerExperienceXeboRoute
  '/cybersecurity/barracuda': typeof CybersecurityBarracudaRoute
  '/cybersecurity/firecompass': typeof CybersecurityFirecompassRoute
  '/cybersecurity/microsoft-security': typeof CybersecurityMicrosoftSecurityRoute
  '/cybersecurity/threatdown': typeof CybersecurityThreatdownRoute
  '/microsoft/azure': typeof MicrosoftAzureRoute
  '/microsoft/d365-bc': typeof MicrosoftD365BcRoute
  '/microsoft/d365-crm': typeof MicrosoftD365CrmRoute
  '/microsoft/d365-fo': typeof MicrosoftD365FoRoute
  '/microsoft/power-apps': typeof MicrosoftPowerAppsRoute
  '/microsoft/power-bi': typeof MicrosoftPowerBiRoute
  '/resources/blogs': typeof ResourcesBlogsRouteWithChildren
  '/resources/case-studies': typeof ResourcesCaseStudiesRouteWithChildren
  '/resources/events-webinars': typeof ResourcesEventsWebinarsRouteWithChildren
  '/resources/glossary': typeof ResourcesGlossaryRouteWithChildren
  '/resources/white-papers': typeof ResourcesWhitePapersRouteWithChildren
  '/admin/blogs': typeof AuthenticatedAdminBlogsRouteWithChildren
  '/admin/case-studies': typeof AuthenticatedAdminCaseStudiesRouteWithChildren
  '/admin/events': typeof AuthenticatedAdminEventsRouteWithChildren
  '/admin/glossary': typeof AuthenticatedAdminGlossaryRouteWithChildren
  '/admin/users': typeof AuthenticatedAdminUsersRoute
  '/admin/white-papers': typeof AuthenticatedAdminWhitePapersRouteWithChildren
  '/resources/blogs/$slug': typeof ResourcesBlogsSlugRoute
  '/resources/case-studies/$slug': typeof ResourcesCaseStudiesSlugRoute
  '/resources/events-webinars/$slug': typeof ResourcesEventsWebinarsSlugRoute
  '/resources/glossary/$slug': typeof ResourcesGlossarySlugRoute
  '/resources/white-papers/$slug': typeof ResourcesWhitePapersSlugRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/admin/blogs/$id': typeof AuthenticatedAdminBlogsIdRoute
  '/admin/blogs/new': typeof AuthenticatedAdminBlogsNewRoute
  '/admin/case-studies/$id': typeof AuthenticatedAdminCaseStudiesIdRoute
  '/admin/case-studies/new': typeof AuthenticatedAdminCaseStudiesNewRoute
  '/admin/events/$id': typeof AuthenticatedAdminEventsIdRoute
  '/admin/events/new': typeof AuthenticatedAdminEventsNewRoute
  '/admin/glossary/$id': typeof AuthenticatedAdminGlossaryIdRoute
  '/admin/glossary/new': typeof AuthenticatedAdminGlossaryNewRoute
  '/admin/white-papers/$id': typeof AuthenticatedAdminWhitePapersIdRoute
  '/admin/white-papers/new': typeof AuthenticatedAdminWhitePapersNewRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/v2': typeof V2Route
  '/ai/dune-dynamics': typeof AiDuneDynamicsRoute
  '/ai/provakil': typeof AiProvakilRoute
  '/customer-experience/view360': typeof CustomerExperienceView360Route
  '/customer-experience/xebo': typeof CustomerExperienceXeboRoute
  '/cybersecurity/barracuda': typeof CybersecurityBarracudaRoute
  '/cybersecurity/firecompass': typeof CybersecurityFirecompassRoute
  '/cybersecurity/microsoft-security': typeof CybersecurityMicrosoftSecurityRoute
  '/cybersecurity/threatdown': typeof CybersecurityThreatdownRoute
  '/microsoft/azure': typeof MicrosoftAzureRoute
  '/microsoft/d365-bc': typeof MicrosoftD365BcRoute
  '/microsoft/d365-crm': typeof MicrosoftD365CrmRoute
  '/microsoft/d365-fo': typeof MicrosoftD365FoRoute
  '/microsoft/power-apps': typeof MicrosoftPowerAppsRoute
  '/microsoft/power-bi': typeof MicrosoftPowerBiRoute
  '/resources/blogs': typeof ResourcesBlogsRouteWithChildren
  '/resources/case-studies': typeof ResourcesCaseStudiesRouteWithChildren
  '/resources/events-webinars': typeof ResourcesEventsWebinarsRouteWithChildren
  '/resources/glossary': typeof ResourcesGlossaryRouteWithChildren
  '/resources/white-papers': typeof ResourcesWhitePapersRouteWithChildren
  '/admin/blogs': typeof AuthenticatedAdminBlogsRouteWithChildren
  '/admin/case-studies': typeof AuthenticatedAdminCaseStudiesRouteWithChildren
  '/admin/events': typeof AuthenticatedAdminEventsRouteWithChildren
  '/admin/glossary': typeof AuthenticatedAdminGlossaryRouteWithChildren
  '/admin/users': typeof AuthenticatedAdminUsersRoute
  '/admin/white-papers': typeof AuthenticatedAdminWhitePapersRouteWithChildren
  '/resources/blogs/$slug': typeof ResourcesBlogsSlugRoute
  '/resources/case-studies/$slug': typeof ResourcesCaseStudiesSlugRoute
  '/resources/events-webinars/$slug': typeof ResourcesEventsWebinarsSlugRoute
  '/resources/glossary/$slug': typeof ResourcesGlossarySlugRoute
  '/resources/white-papers/$slug': typeof ResourcesWhitePapersSlugRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/admin/blogs/$id': typeof AuthenticatedAdminBlogsIdRoute
  '/admin/blogs/new': typeof AuthenticatedAdminBlogsNewRoute
  '/admin/case-studies/$id': typeof AuthenticatedAdminCaseStudiesIdRoute
  '/admin/case-studies/new': typeof AuthenticatedAdminCaseStudiesNewRoute
  '/admin/events/$id': typeof AuthenticatedAdminEventsIdRoute
  '/admin/events/new': typeof AuthenticatedAdminEventsNewRoute
  '/admin/glossary/$id': typeof AuthenticatedAdminGlossaryIdRoute
  '/admin/glossary/new': typeof AuthenticatedAdminGlossaryNewRoute
  '/admin/white-papers/$id': typeof AuthenticatedAdminWhitePapersIdRoute
  '/admin/white-papers/new': typeof AuthenticatedAdminWhitePapersNewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/v2': typeof V2Route
  '/_authenticated/admin': typeof AuthenticatedAdminRouteWithChildren
  '/ai/dune-dynamics': typeof AiDuneDynamicsRoute
  '/ai/provakil': typeof AiProvakilRoute
  '/customer-experience/view360': typeof CustomerExperienceView360Route
  '/customer-experience/xebo': typeof CustomerExperienceXeboRoute
  '/cybersecurity/barracuda': typeof CybersecurityBarracudaRoute
  '/cybersecurity/firecompass': typeof CybersecurityFirecompassRoute
  '/cybersecurity/microsoft-security': typeof CybersecurityMicrosoftSecurityRoute
  '/cybersecurity/threatdown': typeof CybersecurityThreatdownRoute
  '/microsoft/azure': typeof MicrosoftAzureRoute
  '/microsoft/d365-bc': typeof MicrosoftD365BcRoute
  '/microsoft/d365-crm': typeof MicrosoftD365CrmRoute
  '/microsoft/d365-fo': typeof MicrosoftD365FoRoute
  '/microsoft/power-apps': typeof MicrosoftPowerAppsRoute
  '/microsoft/power-bi': typeof MicrosoftPowerBiRoute
  '/resources/blogs': typeof ResourcesBlogsRouteWithChildren
  '/resources/case-studies': typeof ResourcesCaseStudiesRouteWithChildren
  '/resources/events-webinars': typeof ResourcesEventsWebinarsRouteWithChildren
  '/resources/glossary': typeof ResourcesGlossaryRouteWithChildren
  '/resources/white-papers': typeof ResourcesWhitePapersRouteWithChildren
  '/_authenticated/admin/blogs': typeof AuthenticatedAdminBlogsRouteWithChildren
  '/_authenticated/admin/case-studies': typeof AuthenticatedAdminCaseStudiesRouteWithChildren
  '/_authenticated/admin/events': typeof AuthenticatedAdminEventsRouteWithChildren
  '/_authenticated/admin/glossary': typeof AuthenticatedAdminGlossaryRouteWithChildren
  '/_authenticated/admin/users': typeof AuthenticatedAdminUsersRoute
  '/_authenticated/admin/white-papers': typeof AuthenticatedAdminWhitePapersRouteWithChildren
  '/resources/blogs/$slug': typeof ResourcesBlogsSlugRoute
  '/resources/case-studies/$slug': typeof ResourcesCaseStudiesSlugRoute
  '/resources/events-webinars/$slug': typeof ResourcesEventsWebinarsSlugRoute
  '/resources/glossary/$slug': typeof ResourcesGlossarySlugRoute
  '/resources/white-papers/$slug': typeof ResourcesWhitePapersSlugRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/_authenticated/admin/blogs/$id': typeof AuthenticatedAdminBlogsIdRoute
  '/_authenticated/admin/blogs/new': typeof AuthenticatedAdminBlogsNewRoute
  '/_authenticated/admin/case-studies/$id': typeof AuthenticatedAdminCaseStudiesIdRoute
  '/_authenticated/admin/case-studies/new': typeof AuthenticatedAdminCaseStudiesNewRoute
  '/_authenticated/admin/events/$id': typeof AuthenticatedAdminEventsIdRoute
  '/_authenticated/admin/events/new': typeof AuthenticatedAdminEventsNewRoute
  '/_authenticated/admin/glossary/$id': typeof AuthenticatedAdminGlossaryIdRoute
  '/_authenticated/admin/glossary/new': typeof AuthenticatedAdminGlossaryNewRoute
  '/_authenticated/admin/white-papers/$id': typeof AuthenticatedAdminWhitePapersIdRoute
  '/_authenticated/admin/white-papers/new': typeof AuthenticatedAdminWhitePapersNewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/auth'
    | '/v2'
    | '/admin'
    | '/ai/dune-dynamics'
    | '/ai/provakil'
    | '/customer-experience/view360'
    | '/customer-experience/xebo'
    | '/cybersecurity/barracuda'
    | '/cybersecurity/firecompass'
    | '/cybersecurity/microsoft-security'
    | '/cybersecurity/threatdown'
    | '/microsoft/azure'
    | '/microsoft/d365-bc'
    | '/microsoft/d365-crm'
    | '/microsoft/d365-fo'
    | '/microsoft/power-apps'
    | '/microsoft/power-bi'
    | '/resources/blogs'
    | '/resources/case-studies'
    | '/resources/events-webinars'
    | '/resources/glossary'
    | '/resources/white-papers'
    | '/admin/blogs'
    | '/admin/case-studies'
    | '/admin/events'
    | '/admin/glossary'
    | '/admin/users'
    | '/admin/white-papers'
    | '/resources/blogs/$slug'
    | '/resources/case-studies/$slug'
    | '/resources/events-webinars/$slug'
    | '/resources/glossary/$slug'
    | '/resources/white-papers/$slug'
    | '/admin/'
    | '/admin/blogs/$id'
    | '/admin/blogs/new'
    | '/admin/case-studies/$id'
    | '/admin/case-studies/new'
    | '/admin/events/$id'
    | '/admin/events/new'
    | '/admin/glossary/$id'
    | '/admin/glossary/new'
    | '/admin/white-papers/$id'
    | '/admin/white-papers/new'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/auth'
    | '/v2'
    | '/ai/dune-dynamics'
    | '/ai/provakil'
    | '/customer-experience/view360'
    | '/customer-experience/xebo'
    | '/cybersecurity/barracuda'
    | '/cybersecurity/firecompass'
    | '/cybersecurity/microsoft-security'
    | '/cybersecurity/threatdown'
    | '/microsoft/azure'
    | '/microsoft/d365-bc'
    | '/microsoft/d365-crm'
    | '/microsoft/d365-fo'
    | '/microsoft/power-apps'
    | '/microsoft/power-bi'
    | '/resources/blogs'
    | '/resources/case-studies'
    | '/resources/events-webinars'
    | '/resources/glossary'
    | '/resources/white-papers'
    | '/admin/blogs'
    | '/admin/case-studies'
    | '/admin/events'
    | '/admin/glossary'
    | '/admin/users'
    | '/admin/white-papers'
    | '/resources/blogs/$slug'
    | '/resources/case-studies/$slug'
    | '/resources/events-webinars/$slug'
    | '/resources/glossary/$slug'
    | '/resources/white-papers/$slug'
    | '/admin'
    | '/admin/blogs/$id'
    | '/admin/blogs/new'
    | '/admin/case-studies/$id'
    | '/admin/case-studies/new'
    | '/admin/events/$id'
    | '/admin/events/new'
    | '/admin/glossary/$id'
    | '/admin/glossary/new'
    | '/admin/white-papers/$id'
    | '/admin/white-papers/new'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/about'
    | '/auth'
    | '/v2'
    | '/_authenticated/admin'
    | '/ai/dune-dynamics'
    | '/ai/provakil'
    | '/customer-experience/view360'
    | '/customer-experience/xebo'
    | '/cybersecurity/barracuda'
    | '/cybersecurity/firecompass'
    | '/cybersecurity/microsoft-security'
    | '/cybersecurity/threatdown'
    | '/microsoft/azure'
    | '/microsoft/d365-bc'
    | '/microsoft/d365-crm'
    | '/microsoft/d365-fo'
    | '/microsoft/power-apps'
    | '/microsoft/power-bi'
    | '/resources/blogs'
    | '/resources/case-studies'
    | '/resources/events-webinars'
    | '/resources/glossary'
    | '/resources/white-papers'
    | '/_authenticated/admin/blogs'
    | '/_authenticated/admin/case-studies'
    | '/_authenticated/admin/events'
    | '/_authenticated/admin/glossary'
    | '/_authenticated/admin/users'
    | '/_authenticated/admin/white-papers'
    | '/resources/blogs/$slug'
    | '/resources/case-studies/$slug'
    | '/resources/events-webinars/$slug'
    | '/resources/glossary/$slug'
    | '/resources/white-papers/$slug'
    | '/_authenticated/admin/'
    | '/_authenticated/admin/blogs/$id'
    | '/_authenticated/admin/blogs/new'
    | '/_authenticated/admin/case-studies/$id'
    | '/_authenticated/admin/case-studies/new'
    | '/_authenticated/admin/events/$id'
    | '/_authenticated/admin/events/new'
    | '/_authenticated/admin/glossary/$id'
    | '/_authenticated/admin/glossary/new'
    | '/_authenticated/admin/white-papers/$id'
    | '/_authenticated/admin/white-papers/new'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AboutRoute: typeof AboutRoute
  AuthRoute: typeof AuthRoute
  V2Route: typeof V2Route
  AiDuneDynamicsRoute: typeof AiDuneDynamicsRoute
  AiProvakilRoute: typeof AiProvakilRoute
  CustomerExperienceView360Route: typeof CustomerExperienceView360Route
  CustomerExperienceXeboRoute: typeof CustomerExperienceXeboRoute
  CybersecurityBarracudaRoute: typeof CybersecurityBarracudaRoute
  CybersecurityFirecompassRoute: typeof CybersecurityFirecompassRoute
  CybersecurityMicrosoftSecurityRoute: typeof CybersecurityMicrosoftSecurityRoute
  CybersecurityThreatdownRoute: typeof CybersecurityThreatdownRoute
  MicrosoftAzureRoute: typeof MicrosoftAzureRoute
  MicrosoftD365BcRoute: typeof MicrosoftD365BcRoute
  MicrosoftD365CrmRoute: typeof MicrosoftD365CrmRoute
  MicrosoftD365FoRoute: typeof MicrosoftD365FoRoute
  MicrosoftPowerAppsRoute: typeof MicrosoftPowerAppsRoute
  MicrosoftPowerBiRoute: typeof MicrosoftPowerBiRoute
  ResourcesBlogsRoute: typeof ResourcesBlogsRouteWithChildren
  ResourcesCaseStudiesRoute: typeof ResourcesCaseStudiesRouteWithChildren
  ResourcesEventsWebinarsRoute: typeof ResourcesEventsWebinarsRouteWithChildren
  ResourcesGlossaryRoute: typeof ResourcesGlossaryRouteWithChildren
  ResourcesWhitePapersRoute: typeof ResourcesWhitePapersRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/v2': {
      id: '/v2'
      path: '/v2'
      fullPath: '/v2'
      preLoaderRoute: typeof V2RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resources/white-papers': {
      id: '/resources/white-papers'
      path: '/resources/white-papers'
      fullPath: '/resources/white-papers'
      preLoaderRoute: typeof ResourcesWhitePapersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resources/glossary': {
      id: '/resources/glossary'
      path: '/resources/glossary'
      fullPath: '/resources/glossary'
      preLoaderRoute: typeof ResourcesGlossaryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resources/events-webinars': {
      id: '/resources/events-webinars'
      path: '/resources/events-webinars'
      fullPath: '/resources/events-webinars'
      preLoaderRoute: typeof ResourcesEventsWebinarsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resources/case-studies': {
      id: '/resources/case-studies'
      path: '/resources/case-studies'
      fullPath: '/resources/case-studies'
      preLoaderRoute: typeof ResourcesCaseStudiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resources/blogs': {
      id: '/resources/blogs'
      path: '/resources/blogs'
      fullPath: '/resources/blogs'
      preLoaderRoute: typeof ResourcesBlogsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/microsoft/power-bi': {
      id: '/microsoft/power-bi'
      path: '/microsoft/power-bi'
      fullPath: '/microsoft/power-bi'
      preLoaderRoute: typeof MicrosoftPowerBiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/microsoft/power-apps': {
      id: '/microsoft/power-apps'
      path: '/microsoft/power-apps'
      fullPath: '/microsoft/power-apps'
      preLoaderRoute: typeof MicrosoftPowerAppsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/microsoft/d365-fo': {
      id: '/microsoft/d365-fo'
      path: '/microsoft/d365-fo'
      fullPath: '/microsoft/d365-fo'
      preLoaderRoute: typeof MicrosoftD365FoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/microsoft/d365-crm': {
      id: '/microsoft/d365-crm'
      path: '/microsoft/d365-crm'
      fullPath: '/microsoft/d365-crm'
      preLoaderRoute: typeof MicrosoftD365CrmRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/microsoft/d365-bc': {
      id: '/microsoft/d365-bc'
      path: '/microsoft/d365-bc'
      fullPath: '/microsoft/d365-bc'
      preLoaderRoute: typeof MicrosoftD365BcRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/microsoft/azure': {
      id: '/microsoft/azure'
      path: '/microsoft/azure'
      fullPath: '/microsoft/azure'
      preLoaderRoute: typeof MicrosoftAzureRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cybersecurity/threatdown': {
      id: '/cybersecurity/threatdown'
      path: '/cybersecurity/threatdown'
      fullPath: '/cybersecurity/threatdown'
      preLoaderRoute: typeof CybersecurityThreatdownRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cybersecurity/microsoft-security': {
      id: '/cybersecurity/microsoft-security'
      path: '/cybersecurity/microsoft-security'
      fullPath: '/cybersecurity/microsoft-security'
      preLoaderRoute: typeof CybersecurityMicrosoftSecurityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cybersecurity/firecompass': {
      id: '/cybersecurity/firecompass'
      path: '/cybersecurity/firecompass'
      fullPath: '/cybersecurity/firecompass'
      preLoaderRoute: typeof CybersecurityFirecompassRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cybersecurity/barracuda': {
      id: '/cybersecurity/barracuda'
      path: '/cybersecurity/barracuda'
      fullPath: '/cybersecurity/barracuda'
      preLoaderRoute: typeof CybersecurityBarracudaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customer-experience/xebo': {
      id: '/customer-experience/xebo'
      path: '/customer-experience/xebo'
      fullPath: '/customer-experience/xebo'
      preLoaderRoute: typeof CustomerExperienceXeboRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customer-experience/view360': {
      id: '/customer-experience/view360'
      path: '/customer-experience/view360'
      fullPath: '/customer-experience/view360'
      preLoaderRoute: typeof CustomerExperienceView360RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai/provakil': {
      id: '/ai/provakil'
      path: '/ai/provakil'
      fullPath: '/ai/provakil'
      preLoaderRoute: typeof AiProvakilRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai/dune-dynamics': {
      id: '/ai/dune-dynamics'
      path: '/ai/dune-dynamics'
      fullPath: '/ai/dune-dynamics'
      preLoaderRoute: typeof AiDuneDynamicsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/resources/white-papers/$slug': {
      id: '/resources/white-papers/$slug'
      path: '/$slug'
      fullPath: '/resources/white-papers/$slug'
      preLoaderRoute: typeof ResourcesWhitePapersSlugRouteImport
      parentRoute: typeof ResourcesWhitePapersRoute
    }
    '/resources/glossary/$slug': {
      id: '/resources/glossary/$slug'
      path: '/$slug'
      fullPath: '/resources/glossary/$slug'
      preLoaderRoute: typeof ResourcesGlossarySlugRouteImport
      parentRoute: typeof ResourcesGlossaryRoute
    }
    '/resources/events-webinars/$slug': {
      id: '/resources/events-webinars/$slug'
      path: '/$slug'
      fullPath: '/resources/events-webinars/$slug'
      preLoaderRoute: typeof ResourcesEventsWebinarsSlugRouteImport
      parentRoute: typeof ResourcesEventsWebinarsRoute
    }
    '/resources/case-studies/$slug': {
      id: '/resources/case-studies/$slug'
      path: '/$slug'
      fullPath: '/resources/case-studies/$slug'
      preLoaderRoute: typeof ResourcesCaseStudiesSlugRouteImport
      parentRoute: typeof ResourcesCaseStudiesRoute
    }
    '/resources/blogs/$slug': {
      id: '/resources/blogs/$slug'
      path: '/$slug'
      fullPath: '/resources/blogs/$slug'
      preLoaderRoute: typeof ResourcesBlogsSlugRouteImport
      parentRoute: typeof ResourcesBlogsRoute
    }
    '/_authenticated/admin/white-papers': {
      id: '/_authenticated/admin/white-papers'
      path: '/white-papers'
      fullPath: '/admin/white-papers'
      preLoaderRoute: typeof AuthenticatedAdminWhitePapersRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/users': {
      id: '/_authenticated/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AuthenticatedAdminUsersRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/glossary': {
      id: '/_authenticated/admin/glossary'
      path: '/glossary'
      fullPath: '/admin/glossary'
      preLoaderRoute: typeof AuthenticatedAdminGlossaryRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/events': {
      id: '/_authenticated/admin/events'
      path: '/events'
      fullPath: '/admin/events'
      preLoaderRoute: typeof AuthenticatedAdminEventsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/case-studies': {
      id: '/_authenticated/admin/case-studies'
      path: '/case-studies'
      fullPath: '/admin/case-studies'
      preLoaderRoute: typeof AuthenticatedAdminCaseStudiesRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/blogs': {
      id: '/_authenticated/admin/blogs'
      path: '/blogs'
      fullPath: '/admin/blogs'
      preLoaderRoute: typeof AuthenticatedAdminBlogsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/white-papers/new': {
      id: '/_authenticated/admin/white-papers/new'
      path: '/new'
      fullPath: '/admin/white-papers/new'
      preLoaderRoute: typeof AuthenticatedAdminWhitePapersNewRouteImport
      parentRoute: typeof AuthenticatedAdminWhitePapersRoute
    }
    '/_authenticated/admin/white-papers/$id': {
      id: '/_authenticated/admin/white-papers/$id'
      path: '/$id'
      fullPath: '/admin/white-papers/$id'
      preLoaderRoute: typeof AuthenticatedAdminWhitePapersIdRouteImport
      parentRoute: typeof AuthenticatedAdminWhitePapersRoute
    }
    '/_authenticated/admin/glossary/new': {
      id: '/_authenticated/admin/glossary/new'
      path: '/new'
      fullPath: '/admin/glossary/new'
      preLoaderRoute: typeof AuthenticatedAdminGlossaryNewRouteImport
      parentRoute: typeof AuthenticatedAdminGlossaryRoute
    }
    '/_authenticated/admin/glossary/$id': {
      id: '/_authenticated/admin/glossary/$id'
      path: '/$id'
      fullPath: '/admin/glossary/$id'
      preLoaderRoute: typeof AuthenticatedAdminGlossaryIdRouteImport
      parentRoute: typeof AuthenticatedAdminGlossaryRoute
    }
    '/_authenticated/admin/events/new': {
      id: '/_authenticated/admin/events/new'
      path: '/new'
      fullPath: '/admin/events/new'
      preLoaderRoute: typeof AuthenticatedAdminEventsNewRouteImport
      parentRoute: typeof AuthenticatedAdminEventsRoute
    }
    '/_authenticated/admin/events/$id': {
      id: '/_authenticated/admin/events/$id'
      path: '/$id'
      fullPath: '/admin/events/$id'
      preLoaderRoute: typeof AuthenticatedAdminEventsIdRouteImport
      parentRoute: typeof AuthenticatedAdminEventsRoute
    }
    '/_authenticated/admin/case-studies/new': {
      id: '/_authenticated/admin/case-studies/new'
      path: '/new'
      fullPath: '/admin/case-studies/new'
      preLoaderRoute: typeof AuthenticatedAdminCaseStudiesNewRouteImport
      parentRoute: typeof AuthenticatedAdminCaseStudiesRoute
    }
    '/_authenticated/admin/case-studies/$id': {
      id: '/_authenticated/admin/case-studies/$id'
      path: '/$id'
      fullPath: '/admin/case-studies/$id'
      preLoaderRoute: typeof AuthenticatedAdminCaseStudiesIdRouteImport
      parentRoute: typeof AuthenticatedAdminCaseStudiesRoute
    }
    '/_authenticated/admin/blogs/new': {
      id: '/_authenticated/admin/blogs/new'
      path: '/new'
      fullPath: '/admin/blogs/new'
      preLoaderRoute: typeof AuthenticatedAdminBlogsNewRouteImport
      parentRoute: typeof AuthenticatedAdminBlogsRoute
    }
    '/_authenticated/admin/blogs/$id': {
      id: '/_authenticated/admin/blogs/$id'
      path: '/$id'
      fullPath: '/admin/blogs/$id'
      preLoaderRoute: typeof AuthenticatedAdminBlogsIdRouteImport
      parentRoute: typeof AuthenticatedAdminBlogsRoute
    }
  }
}

interface AuthenticatedAdminBlogsRouteChildren {
  AuthenticatedAdminBlogsIdRoute: typeof AuthenticatedAdminBlogsIdRoute
  AuthenticatedAdminBlogsNewRoute: typeof AuthenticatedAdminBlogsNewRoute
}

const AuthenticatedAdminBlogsRouteChildren: AuthenticatedAdminBlogsRouteChildren =
  {
    AuthenticatedAdminBlogsIdRoute: AuthenticatedAdminBlogsIdRoute,
    AuthenticatedAdminBlogsNewRoute: AuthenticatedAdminBlogsNewRoute,
  }

const AuthenticatedAdminBlogsRouteWithChildren =
  AuthenticatedAdminBlogsRoute._addFileChildren(
    AuthenticatedAdminBlogsRouteChildren,
  )

interface AuthenticatedAdminCaseStudiesRouteChildren {
  AuthenticatedAdminCaseStudiesIdRoute: typeof AuthenticatedAdminCaseStudiesIdRoute
  AuthenticatedAdminCaseStudiesNewRoute: typeof AuthenticatedAdminCaseStudiesNewRoute
}

const AuthenticatedAdminCaseStudiesRouteChildren: AuthenticatedAdminCaseStudiesRouteChildren =
  {
    AuthenticatedAdminCaseStudiesIdRoute: AuthenticatedAdminCaseStudiesIdRoute,
    AuthenticatedAdminCaseStudiesNewRoute:
      AuthenticatedAdminCaseStudiesNewRoute,
  }

const AuthenticatedAdminCaseStudiesRouteWithChildren =
  AuthenticatedAdminCaseStudiesRoute._addFileChildren(
    AuthenticatedAdminCaseStudiesRouteChildren,
  )

interface AuthenticatedAdminEventsRouteChildren {
  AuthenticatedAdminEventsIdRoute: typeof AuthenticatedAdminEventsIdRoute
  AuthenticatedAdminEventsNewRoute: typeof AuthenticatedAdminEventsNewRoute
}

const AuthenticatedAdminEventsRouteChildren: AuthenticatedAdminEventsRouteChildren =
  {
    AuthenticatedAdminEventsIdRoute: AuthenticatedAdminEventsIdRoute,
    AuthenticatedAdminEventsNewRoute: AuthenticatedAdminEventsNewRoute,
  }

const AuthenticatedAdminEventsRouteWithChildren =
  AuthenticatedAdminEventsRoute._addFileChildren(
    AuthenticatedAdminEventsRouteChildren,
  )

interface AuthenticatedAdminGlossaryRouteChildren {
  AuthenticatedAdminGlossaryIdRoute: typeof AuthenticatedAdminGlossaryIdRoute
  AuthenticatedAdminGlossaryNewRoute: typeof AuthenticatedAdminGlossaryNewRoute
}

const AuthenticatedAdminGlossaryRouteChildren: AuthenticatedAdminGlossaryRouteChildren =
  {
    AuthenticatedAdminGlossaryIdRoute: AuthenticatedAdminGlossaryIdRoute,
    AuthenticatedAdminGlossaryNewRoute: AuthenticatedAdminGlossaryNewRoute,
  }

const AuthenticatedAdminGlossaryRouteWithChildren =
  AuthenticatedAdminGlossaryRoute._addFileChildren(
    AuthenticatedAdminGlossaryRouteChildren,
  )

interface AuthenticatedAdminWhitePapersRouteChildren {
  AuthenticatedAdminWhitePapersIdRoute: typeof AuthenticatedAdminWhitePapersIdRoute
  AuthenticatedAdminWhitePapersNewRoute: typeof AuthenticatedAdminWhitePapersNewRoute
}

const AuthenticatedAdminWhitePapersRouteChildren: AuthenticatedAdminWhitePapersRouteChildren =
  {
    AuthenticatedAdminWhitePapersIdRoute: AuthenticatedAdminWhitePapersIdRoute,
    AuthenticatedAdminWhitePapersNewRoute:
      AuthenticatedAdminWhitePapersNewRoute,
  }

const AuthenticatedAdminWhitePapersRouteWithChildren =
  AuthenticatedAdminWhitePapersRoute._addFileChildren(
    AuthenticatedAdminWhitePapersRouteChildren,
  )

interface AuthenticatedAdminRouteChildren {
  AuthenticatedAdminBlogsRoute: typeof AuthenticatedAdminBlogsRouteWithChildren
  AuthenticatedAdminCaseStudiesRoute: typeof AuthenticatedAdminCaseStudiesRouteWithChildren
  AuthenticatedAdminEventsRoute: typeof AuthenticatedAdminEventsRouteWithChildren
  AuthenticatedAdminGlossaryRoute: typeof AuthenticatedAdminGlossaryRouteWithChildren
  AuthenticatedAdminUsersRoute: typeof AuthenticatedAdminUsersRoute
  AuthenticatedAdminWhitePapersRoute: typeof AuthenticatedAdminWhitePapersRouteWithChildren
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
}

const AuthenticatedAdminRouteChildren: AuthenticatedAdminRouteChildren = {
  AuthenticatedAdminBlogsRoute: AuthenticatedAdminBlogsRouteWithChildren,
  AuthenticatedAdminCaseStudiesRoute:
    AuthenticatedAdminCaseStudiesRouteWithChildren,
  AuthenticatedAdminEventsRoute: AuthenticatedAdminEventsRouteWithChildren,
  AuthenticatedAdminGlossaryRoute: AuthenticatedAdminGlossaryRouteWithChildren,
  AuthenticatedAdminUsersRoute: AuthenticatedAdminUsersRoute,
  AuthenticatedAdminWhitePapersRoute:
    AuthenticatedAdminWhitePapersRouteWithChildren,
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
}

const AuthenticatedAdminRouteWithChildren =
  AuthenticatedAdminRoute._addFileChildren(AuthenticatedAdminRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRouteWithChildren
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRouteWithChildren,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface ResourcesBlogsRouteChildren {
  ResourcesBlogsSlugRoute: typeof ResourcesBlogsSlugRoute
}

const ResourcesBlogsRouteChildren: ResourcesBlogsRouteChildren = {
  ResourcesBlogsSlugRoute: ResourcesBlogsSlugRoute,
}

const ResourcesBlogsRouteWithChildren = ResourcesBlogsRoute._addFileChildren(
  ResourcesBlogsRouteChildren,
)

interface ResourcesCaseStudiesRouteChildren {
  ResourcesCaseStudiesSlugRoute: typeof ResourcesCaseStudiesSlugRoute
}

const ResourcesCaseStudiesRouteChildren: ResourcesCaseStudiesRouteChildren = {
  ResourcesCaseStudiesSlugRoute: ResourcesCaseStudiesSlugRoute,
}

const ResourcesCaseStudiesRouteWithChildren =
  ResourcesCaseStudiesRoute._addFileChildren(ResourcesCaseStudiesRouteChildren)

interface ResourcesEventsWebinarsRouteChildren {
  ResourcesEventsWebinarsSlugRoute: typeof ResourcesEventsWebinarsSlugRoute
}

const ResourcesEventsWebinarsRouteChildren: ResourcesEventsWebinarsRouteChildren =
  {
    ResourcesEventsWebinarsSlugRoute: ResourcesEventsWebinarsSlugRoute,
  }

const ResourcesEventsWebinarsRouteWithChildren =
  ResourcesEventsWebinarsRoute._addFileChildren(
    ResourcesEventsWebinarsRouteChildren,
  )

interface ResourcesGlossaryRouteChildren {
  ResourcesGlossarySlugRoute: typeof ResourcesGlossarySlugRoute
}

const ResourcesGlossaryRouteChildren: ResourcesGlossaryRouteChildren = {
  ResourcesGlossarySlugRoute: ResourcesGlossarySlugRoute,
}

const ResourcesGlossaryRouteWithChildren =
  ResourcesGlossaryRoute._addFileChildren(ResourcesGlossaryRouteChildren)

interface ResourcesWhitePapersRouteChildren {
  ResourcesWhitePapersSlugRoute: typeof ResourcesWhitePapersSlugRoute
}

const ResourcesWhitePapersRouteChildren: ResourcesWhitePapersRouteChildren = {
  ResourcesWhitePapersSlugRoute: ResourcesWhitePapersSlugRoute,
}

const ResourcesWhitePapersRouteWithChildren =
  ResourcesWhitePapersRoute._addFileChildren(ResourcesWhitePapersRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AboutRoute: AboutRoute,
  AuthRoute: AuthRoute,
  V2Route: V2Route,
  AiDuneDynamicsRoute: AiDuneDynamicsRoute,
  AiProvakilRoute: AiProvakilRoute,
  CustomerExperienceView360Route: CustomerExperienceView360Route,
  CustomerExperienceXeboRoute: CustomerExperienceXeboRoute,
  CybersecurityBarracudaRoute: CybersecurityBarracudaRoute,
  CybersecurityFirecompassRoute: CybersecurityFirecompassRoute,
  CybersecurityMicrosoftSecurityRoute: CybersecurityMicrosoftSecurityRoute,
  CybersecurityThreatdownRoute: CybersecurityThreatdownRoute,
  MicrosoftAzureRoute: MicrosoftAzureRoute,
  MicrosoftD365BcRoute: MicrosoftD365BcRoute,
  MicrosoftD365CrmRoute: MicrosoftD365CrmRoute,
  MicrosoftD365FoRoute: MicrosoftD365FoRoute,
  MicrosoftPowerAppsRoute: MicrosoftPowerAppsRoute,
  MicrosoftPowerBiRoute: MicrosoftPowerBiRoute,
  ResourcesBlogsRoute: ResourcesBlogsRouteWithChildren,
  ResourcesCaseStudiesRoute: ResourcesCaseStudiesRouteWithChildren,
  ResourcesEventsWebinarsRoute: ResourcesEventsWebinarsRouteWithChildren,
  ResourcesGlossaryRoute: ResourcesGlossaryRouteWithChildren,
  ResourcesWhitePapersRoute: ResourcesWhitePapersRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
